# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-22 06:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='session_inx',
        ),
        migrations.AlterField(
            model_name='log',
            name='content_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='log',
            name='user_id',
            field=models.IntegerField(),
        ),
    ]
