# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-17 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=128)),
                ('year', models.IntegerField()),
                ('genre', models.CharField(max_length=128)),
            ],
        ),
    ]
