# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-17 12:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moviegeeks', '0002_auto_20160517_1255'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='id',
            new_name='movie_id',
        ),
    ]
