# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-19 18:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviegeeks', '0006_auto_20160517_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genres',
            field=models.ManyToManyField(db_table='movie_genre', related_name='movies', to='moviegeeks.Genre'),
        ),
    ]
